### ISSUE TITLE
Another undefined property error

### ISSUE THREAD

**Issue by daniil-berg** [innocampus/moodle-quizaccess_watermark#7]
https://github.com/innocampus/moodle-quizaccess_watermark/blob/181c961a3bfeaa091d61f13f3af73001516e81bf/rule.php#L126

Same as issue #2. Overlooked in PR #4.

**Comment by MartinGauk** [comment]
Where exactly does it occur?
This indicates that the form elements defined by `add_settings_form_fields` were not added. Otherwise I would always expect this property to be set.

**Comment by daniil-berg** [comment]
In the quiz unit tests, if I recall correctly. I'll need to verify exactly, but I believe it has to do with the quiz test instance generator not using the accessrule form fields, but the [`access_manager::save_settings`](https://github.com/moodle/moodle/blob/554a790bf0a22eb3811d3e28e3a453720ffacb60/mod/quiz/classes/access_manager.php#L164) method still being called. I definitely remember the stack trace ending at the line mentioned above though.

Either way, for type safety reasons it is probably a good idea to use `null`-coalescing in these situations. I know this is a drop in the bucket since Moodle throws `stdClass` objects at us, which means we technically cannot even be sure that e.g. the `id` property exists. But at least we would cover _our_ bases, by making sure that _our_ dynamically-defined properties are actually present.
